import random

# list of possible backgrounds and associated talents/skills
background_data = [
    "adventurer",
    "veteran soldier",
    "academy trainee",
    "academy dropout",
    "consort to some ruler",
    "grizzled field medic",
    "cat burgler",
    "street urchin",
    "wizard's apprentice",
    "gravedigger",
    "hermitic woodsman",
    "journeyman smith",
    "master smith",
    "apprentice tailor",
    "journeyman tailor",
    "master tailor",
    "apprentice sommelier",
    "journeyman sommelier",
    "master sommelier",
    "apprentice brewer",
    "journeyman brewer",
    "master brewer",
    "innkeep",
    "ageless carvaneer",
    "amateur cartographer",
    "assassin of assassins",
    "battlefield scavenger",
    "beast whisperer",
    "beggar queen’s scion",
    "bone-fortifying technique",
    "born at sea",
    "vagrant",
    "itinerant",
    "calculating liar",
    "champion stitcherman",
    "child of exiled vizier",
    "city vigilant",
    "collector of recipes",
    "colossal beast herder",
    "covert infiltrator",
    "dedicated scribbler",
    "deep diver",
    "disappointed ancestral advisor",
    "disavowed squire",
    "disillusioned officer",
    "dungeon poacher",
    "emergency sawbones",
    "escaped the purges",
    "experienced rabble-rouser",
    "expert gamesman",
    "fairy exterminator",
    "fallen exorcist",
    "fashion paragon",
    "fearsome debater",
    "finder for hire",
    "foreign interpreter",
    "foremost etiquette expert",
    "former undead",
    "freehand tower cleaner",
    "genealogist",
    "geomatic architect",
    "ghost breaker",
    "god game gladiator",
    "godsmith apprentice",
    "heretic musician",
    "holy wrestler",
    "hunger artist",
    "indentured to elementals",
    "infamous trapsmith",
    "ink-stained bookworm",
    "jailer of the infamous",
    "keeper of lost tongues",
    "life in the rigging",
    "long-haul navigator",
    "longtime imposter",
    "magical fisherman",
    "master of marches",
    "mercenary wisdom",
    "minster of small things",
    "mistress of revels",
    "mudlark",
    "network of conspirators",
    "nomadic herdmaster",
    "notorious executioner",
    "oathbound courier",
    "only a few survived being monster bait",
    "outcast by wicked step-parent",
    "overseer of the lists",
    "pearl diver",
    "plague tender",
    "poison gardener",
    "practical sellsword",
    "puzzle master",
    "raised by goblins",
    "recitationist",
    "recovering becursed",
    "reformed cultist",
    "royal statistician",
    "rubble runner",
    "ruthless observer",
    "savant of patterns",
    "scales like a mountain goat",
    "sentinel of the books",
    "seven evil masters",
    "shipwreck survivor",
    "siege survivor",
    "skyship raider",
    "slave pit escapee",
    "smiling fixer",
    "soul vessel",
    "spirit speaker",
    "stalwart guide",
    "stoic bearer",
    "syndicate lookout",
    "taught on the road",
    "tempered by denial",
    "time in the circus",
    "torturer for the god of healing",
    "tunnel rat",
    "veteran pillager",
    "visionary painter",
    "wandering teacher",
    "ward of the thieves guild",
    "warden of the dance",
    "witch farm escapee",
    "years on the wheel of woe",
]

MAX_BACKGROUNDS = 4
MIN_BACKGROUNDS = 1

def main():
    backgrounds = background_data.copy()
    chosen_backgrounds = []

    num_backgrounds = random.randint(MIN_BACKGROUNDS, MAX_BACKGROUNDS)

    while len(chosen_backgrounds) <= num_backgrounds:
        index = random.randint(0, len(backgrounds)-1)
        background = backgrounds[index]
        # avoids duplicates
        del backgrounds[index]
        chosen_backgrounds.append(background)

    return chosen_backgrounds

if __name__ == "__main__":
    result = main()
    print(result)
