language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv install'
script: 'python -m pytest'
notifications:
  email:
    recipients:
    - modle1213@gmail.com
    on_success: always
    on_failure: always
